### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by michelleg06** [coolbutuseless/geomlime#3]
Hi!

I'm trying to install geom_lime(), but I get the following error: 
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`coolbutuseless`) and repo name (`geomlime`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

I am using Mac OS X El Capitan, version 10.11.6, and R version 3.6.2, Rstudio version 1.1.383.

Any help that you can provide to fix this issue will be greatly appreciated!

**Comment by coolbutuseless** [comment]
This may be because the core github branch has changed to 'main' rather than 'master'.

Could you try to explicitly fetch the 'main' branch:  `remotes::install_github('coolbutuseless/geomlime@main')`

**Comment by michelleg06** [comment]
This works! Thanks so much! 

P.S. This is cool and useful! (Keeps me motivated when visualizing data) 👍
